FAC = {}

FAC.Strings = {
	['Kicked'] = {title = 'You have been kicked from the server.', text = 'Contact the staff team for more information.'},
	['Banned'] = {title = 'You Have Been Banned By Furious Anti-Cheat.', text = 'Contact the staff team for more information.'},
	['Reasons'] = {
		BlacklistedWeapon = 'Blacklisted Weapon',
		DamageMultiplier = 'Modified Damage Multiplier',
		MaxAmmo = 'Ammo Capacity Maxed',
        Explosion = 'Malicious Explosion Detected',
		MenuInjection = 'Lua Menu Injection',
		Object = 'Blacklisted Object Detected',
		OnScreenKeyboard = 'On Screen Keyboard Detected',
		VPNDetected = 'VPN connection detected, please disable your vpn and reconnect.',
        BlacklistedNames = 'Blacklisted Name.',
        Executor = 'Executor Detected On Players Screen',
		Invisibility = 'Invisibility Detected',
		Freecam = 'Freecam Detected',
        RemoveWeapon = 'Player tried removing another players gun',
        GiveWeapon = 'Player tried giving another player guns',
		ShrinkPed = 'Shrink Ped Detected',
		Ragdoll = 'Anti Ragdoll Detected', 
		Teleport = 'Player Teleported',
		VehicleSpeed = 'Vehicle Speed Multi Detected',
		MaxVehicles = 'Player Spawned the Max Amount of Vehicles',
		VehicleGodmode = 'Vehicle God Mode Detected',
		VehicleTire = 'Anti Tire Pop Detected',
		Spectate = 'Spectated Another Player',
		Godmode = 'Godmode Detected',
		Nightvision = 'Nightvision Detected',
		Heatvision = 'Heatvision Detected',
		Blips = 'Blips Detected',
		Noclip = 'Noclip Detected',
		Tazers = 'Mass Tazers Detected',
		ResourceStop = 'Player Attempted stop a resource',
		BlacklistedWord = 'Player Attempted to say a blacklisted word',
		FakeChat = 'FakeChat Detected',
		BlacklistedKey = 'Blacklisted Key Pressed',
		BlacklistedTrigger = 'Triggered A Blacklisted Trigger',
		ClearPedTasks = 'Player tried clearing ped task immediatly',
		BlacklistedModel = 'Blacklisted Model Detected',
		PTFX = 'PTFX Detected',
		Radar = 'Radar/Minimap Detected',
	},
}

FAC.Webhooks = {
	Kicks = {
		Enabled = true, --[true or false]
		Webhook = ''
	},
	Bans = {
		Enabled = true, --[true or false]
		Webhook = '' 
	},
	Identifiers = {
		Steam = true, --[true or false]
		License = true, --[true or false]
		Xbox = true, --[true or false]
		Live = true, --[true or false]
		FiveM = true, --[true or false]
		Discord = true, --[true or false]
		IPAddress = false --[true or false]
	}
}
FAC.Screenshot = { -- This Requires You To Have Screenshot-basic
    Enabled = true,
}

FAC.Commands = {
        KickCommand = 'fackick',
        BanCommand = 'facban',
        UnbanCommand = 'facunban',
        WipeCommand = 'facwipe',
}

FAC.OnBannedPlayerJoin = {
        ConsolePrint = true,
        DiscordLog = true,
}

FAC.Info = {
    ServerName = 'ChangeMe',
    Discord = 'discord.gg/ChangeMe'
}

FAC.Tazers = { 
	Enabled = false,
        Punishment = 'none',
	ESX = {
		WhitelistedJobs = {'police', 'offpolice'}
	}
}

FAC.MenuInjection = { --[refer to documentation in discord for full info & details about this feature.]
    Enabled = true, -- [true or false.]
    Punishment = 'ban',
    Sprites = {
        {texture = 'deadline', label = 'Dopamine'},
        {texture = 'darkside', label = 'DarkSide Gang'},
        {texture = 'Tezi', label = 'Tezi'},
        {texture = 'shopui_title_graphics_franklin', label = 'Franklin Menu'},
        {texture = 'digitaloverlay', label = 'digitaloverlay'},
        {texture = 'mpmissmarkers256', label = 'FiveSense'},
        {texture = 'hunting', label = 'hunting'},
        {texture = "HydroMenu", label = "Hydro Menu"},
        {texture = "loganmonreufton", label = "m1000 Menu"},
        {texture = "fm", label = "Fallout Menu"},
        {texture = "loading", label = "Helder Modz"},
        {texture = "absolute", label = "Absolute V2"},
        {texture = "absolute2", label = "Absolute V2"},
        {texture = "absolute3", label = "Absolute V2"},
        {texture = "absolute4", label = "Absolute V2"},
        {texture = "John",label = "Sharks Menu"},
        {texture = "John2", label = "Sharks Menu"},
        {texture = "wave", label = "Wave Menu"},
        {texture = "weapon_icons", label = "Lux Menu"},
        {texture = "Octagon", label = "Octagon Menu"},
        {texture = "Strata", label = "Strata Menu"},
        {texture = "shop_lock", label = "Delux Menu"},
        {texture = "tiagomodz", label = "Tiago Menu"}
    }
}

FAC.Radar = {
	Enabled = false, -- [true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.ShrinkPed = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.Teleport = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.GiveWeapon = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.RemoveWeapon = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.ResourceStop = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.OnScreenKeyboard = {
	Enabled = false,
	Punishment = 'ban'
}

FAC.PTFX = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.VehicleSpeed = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.VehicleGodmode = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.VehicleTires = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.Freecam = {
	Enabled = false,
	Punishment = 'ban', --['kick', 'ban']
}

FAC.Spectate = {
	Enabled = false, --[true or false]
	Punishment = 'ban', --['kick', 'ban']
}

FAC.Nightvision = {
	Enabled = true, --[true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.Heatvision = {
	Enabled = true, --[true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.Godmode = {
	Enabled = true, --[true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.Invisibility = {
	Enabled = false, --[true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.Ragdoll = {
	Enabled = true, --[true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.Blips = { 
	Enabled = true, --[true or false]
	Punishment = 'ban' --['kick', 'ban']
}

FAC.ClearPedTasks = {
	Enabled = true,
	Punishment = 'ban'
}

FAC.Noclip = {  
	Enabled = true,
	Punishment = 'kick'
}

FAC.Chat = {
    FakeChatMessages = {
        Enabled = true,
        Punishment = 'ban'
    },
    BlacklistedWords = {
	    ['brutan'] = {punishment = 'ban'}, 
	    ['desudo'] = {punishment = 'ban'},
        ['n1gger'] = {punishment = 'ban'},
        ['fagg0t'] = {punishment = 'ban'},
        ['Nigger'] = {punishment = 'ban'},
        ['NIGGER'] = {punishment = 'ban'},
        ['N I G G E R'] = {punishment = 'ban'},
        ['n1gg3r'] = {punishment = 'ban'},
        ['N1GG3R'] = {punishment = 'ban'},
        ['Faggot'] = {punishment = 'ban'},
        ['FAGGOT'] = {punishment = 'ban'},
        ['N1ggers'] = {punishment = 'ban'},
        ['n1ggers'] = {punishment = 'ban'},
        ['N1ggers!!!!'] = {punishment = 'ban'},
        ['n1ggers!!!!'] = {punishment = 'ban'},
        ['coons'] = {punishment = 'ban'},
        ['Coons'] = {punishment = 'ban'},
        ['N1ggers!'] = {punishment = 'ban'},
        ['N1ggers!!'] = {punishment = 'ban'},
        ['FaGGoT'] = {punishment = 'ban'},
        ['cracker'] = {punishment = 'ban'},
        ['Cracker'] = {punishment = 'ban'},
        ['FAGGOT!!!'] = {punishment = 'ban'},
        ['FAGGOTS!!!'] = {punishment = 'ban'},
        ['faggots'] = {punishment = 'ban'},
        ['faggots!!!'] = {punishment = 'ban'},
	    ['nigger'] = {punishment = 'ban'},
	    ['faggot'] = {punishment = 'ban'},
	    ['lumia'] = {punishment = 'ban'},
	    ['virgin'] = {punishment = 'kick'}
    }
}

FAC.Names = {
     Enabled = true,
	 Blacklisted = { 
	   'keydrop',
       'rustchance',
	   'hellcase',
	   'eulen',
	   'brutan',
	   'nigger',
	   'moderator',
	   'owner',
	   'nigger',
	   'developer',
       'faggot',

	}
}

FAC.BlacklistedKeys = {
	Enabled = false,
	Keys = {
		[121] = {label = 'Insert Key', punishment = 'ban'},
		[37] = {label = 'Tab Key', punishment = 'ban'},
		[214] = {label = 'Delete Key', punishment = 'ban'},
		[344] = {label = 'F11', punishment = 'ban'},
		[117] = {label = 'Numpad 7 Key', punishment = 'kick'}
	}
}

FAC.Triggers = {
	Enabled = true,
	Triggers = {
	["vrp_slotmachine:server:2"] = {punishment = 'kick'},
	["Banca:deposit"] = {punishment = 'ban'},
	["esx_jobs:caution"] = {punishment = 'ban'},
	["esx_fueldelivery:pay"] = {punishment = 'ban'},
	["esx_carthief:pay"] = {punishment = 'ban'},
	["esx_godirtyjob:pay"] = {punishment = 'ban'},
	["esx_pizza:pay"] = {punishment = 'ban'},
	["esx_ranger:pay"] = {punishment = 'ban'},
	["esx_garbagejob:pay"] = {punishment = 'ban'},
	["esx_truckerjob:pay"] = {punishment = 'ban'},
	["redst0nia:checking"] = {punishment = 'ban'},
	["esx_gopostaljob:pay"] = {punishment = 'ban'},
	["esx_banksecurity:pay"] = {punishment = 'ban'},
	["esx_slotmachine:sv:2"] = {punishment = 'ban'},
	["NB:recruterplayer"] = {punishment = 'ban'},
	["esx_jailer:sendToJail"] = {punishment = 'ban'},
	["js:jailuser"] = {punishment = 'ban'},
	["esx_dmvschool:pay"] = {punishment = 'ban'}, 
	["LegacyFuel:PayFuel"] = {punishment = 'ban'},
	["OG_cuffs:cuffCheckNearest"] = {punishment = 'ban'},
	["CheckHandcuff"] = {punishment = 'ban'},
	["dmv:success"] = {punishment = 'ban'},
	["esx_dmvschool:addLicense"] = {punishment = 'ban'},
	["esx_mechanicjob:startCraft"] = {punishment = 'ban'},
	["esx_society:openBossMenu"] = {punishment = 'ban'},
	["esx_jobs:caution"] = {punishment = 'ban'},
	["esx_tankerjob:pay"] = {punishment = 'ban'},
	["mission:completed"] = {punishment = 'ban'},
	["truckerJob:success"] = {punishment = 'ban'},
	["99kr-burglary:addMoney"] = {punishment = 'ban'},
	["esx_jailer:unjailTime"] = {punishment = 'ban'},
	["hentailover:xdlol"] = {punishment = 'ban'},
	["antilynx8:anticheat"] = {punishment = 'ban'},
	["antilynxr6:detection"] = {punishment = 'ban'},
	["esx_society:getOnlinePlayers"] = {punishment = 'ban'},
	["antilynx8r4a:anticheat"] = {punishment = 'ban'},
	["antilynxr4:detect"] = {punishment = 'ban'},
	["ynx8:anticheat"] = {punishment = 'ban'},
	["lynx8:anticheat"] = {punishment = 'ban'},
	["h:xd"] = {punishment = 'ban'},
	["ljail:jailplayer"] = {punishment = 'ban'},
	["adminmenu:setsalary"] = {punishment = 'ban'},
	["adminmenu:cashoutall"] = {punishment = 'ban'},
	["paycheck:bonus"] = {punishment = 'ban'},
	["paycheck:salary"] = {punishment = 'ban'},
	["HCheat:TempDisableDetection"] = {punishment = 'ban'},
	["esx-qalle-hunting:reward"] = {punishment = 'ban'},
	["esx-qalle-hunting:sell"] = {punishment = 'ban'},
	["esx_mecanojob:onNPCJobCompleted"] = {punishment = 'ban'},
	["BsCuff:Cuff696999"] = {punishment = 'ban'},
	["veh_SR:CheckMoneyForVeh"] = {punishment = 'ban'},
	["esx_carthief:alertcops"] = {punishment = 'ban'},
	["mellotrainer:adminTempBan"] = {punishment = 'ban'},
	["mellotrainer:adminKick"] = {punishment = 'ban'},
	["esx_society:putVehicleInGarage"] = {punishment = 'ban'},
	}
}

FAC.Objects = { -- Please Note If You Have NPCS To Put All To None
--[=================================== BLACKLISTED PROPS ================================]--

	['prop_gas_tank_01a'] = { punishment = 'ban'},
	['prop_gascyl_01a'] = { punishment = 'ban'},
	['p_spinning_anus_s'] = { punishment = 'ban'},
	['dt1_lod_slod3'] = { punishment = 'ban'},
	['dt1_lod_slod3'] = { punishment = 'ban'},
	['cs4_lod_04_slod2'] = { punishment = 'ban'},
	['po1_lod_slod4'] = { punishment = 'ban'},
	['id2_lod_slod4'] = { punishment = 'ban'},
	['ap1_lod_slod4'] = { punishment = 'ban'},
	['sm_lod_slod2_22'] = { punishment = 'ban'},
	['prop_xmas_tree_int'] = { punishment = 'ban'},
	['prop_cs_cardbox_01'] = { punishment = 'ban'},
	['prop_alien_egg_01'] = { punishment = 'ban'},
	['prop_tv_03'] = { punishment = 'ban'},
	['prop_windmill_01_l1'] = { punishment = 'ban'},
	['xs_terrain_set_dyst_01_grnd'] = { punishment = 'ban'},
	['xs_propint2_building_base_03'] = { punishment = 'ban'},
	['xs_propint2_building_05'] = { punishment = 'ban'},
	['xs_propint2_building_01'] = { punishment = 'ban'},
	['hei_id2_lod_slod4'] = { punishment = 'ban'},
	['xm_prop_x17_sub'] = { punishment = 'ban'},
	['prop_gas_tank_01a'] = { punishment = 'ban'},
	['prop_container_05a'] = { punishment = 'ban'},
	['xm_prop_x17_silo_rocket_01'] = { punishment = 'ban'},
	['prop_temp_carrier'] = { punishment = 'ban'},
	['prop_inflategate_01'] = { punishment = 'ban'},
	['ar_prop_ar_tube_4x_l'] = { punishment = 'ban'},
	['ar_prop_ar_bblock_huge_01'] = { punishment = 'ban'},
	['dt1_05_build1_damage'] = { punishment = 'ban'},
	['prop_juicestand'] = { punishment = 'ban'},
	['prop_knife'] = { punishment = 'ban'},
	['p_bloodsplat_s'] = { punishment = 'ban'},
	['prop_gascyl_01a'] = { punishment = 'ban'},
	['prop_gas_05'] = { punishment = 'ban'},
	['prop_cs_dog_lead_2a'] = { punishment = 'ban'},
	['prop_beware_dog_sign'] = { punishment = 'ban'},
	['p_airdancer_01_s'] = { punishment = 'ban'},
	['prop_bikini_disp_03'] = { punishment = 'ban'},
	['imp_prop_impexp_half_cut_rack_01b'] = { punishment = 'ban'},
	['prop_cs_dildo_01'] = { punishment = 'ban'},
	['hei_prop_carrier_radar_1_l1'] = { punishment = 'ban'},
	['v_res_mexball'] = { punishment = 'ban'},
	['prop_rock_1_a'] = { punishment = 'ban'},
	['prop_rock_1_b'] = { punishment = 'ban'},
	['prop_rock_1_c'] = { punishment = 'ban'},
	['prop_rock_1_d'] = { punishment = 'ban'},
	['prop_player_gasmask'] = { punishment = 'ban'},
	['prop_rock_1_e'] = { punishment = 'ban'},
	['prop_rock_1_f'] = { punishment = 'ban'},
	['prop_rock_1_g'] = { punishment = 'ban'},
	['prop_rock_1_h'] = { punishment = 'ban'},
	['prop_test_boulder_01'] = { punishment = 'ban'},
	['prop_test_boulder_02'] = { punishment = 'ban'},
	['prop_test_boulder_03'] = { punishment = 'ban'},
	['prop_test_boulder_04'] = { punishment = 'ban'},
	['apa_mp_apa_crashed_usaf_01a'] = { punishment = 'ban'},
	['ex_prop_exec_crashdp'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_o1_rail_a'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_o1_rail_b'] = { punishment = 'ban'},
	['apa_mp_h_yacht_armchair_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_armchair_03'] = { punishment = 'ban'},
	['apa_mp_h_yacht_armchair_04'] = { punishment = 'ban'},
	['apa_mp_h_yacht_barstool_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_bed_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_bed_02'] = { punishment = 'ban'},
	['apa_mp_h_yacht_coffee_table_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_coffee_table_02'] = { punishment = 'ban'},
	['apa_mp_h_yacht_floor_lamp_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_side_table_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_side_table_02'] = { punishment = 'ban'},
	['apa_mp_h_yacht_sofa_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_sofa_02'] = { punishment = 'ban'},
	['apa_mp_h_yacht_stool_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_strip_chair_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_table_lamp_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_table_lamp_02'] = { punishment = 'ban'},
	['apa_mp_h_yacht_table_lamp_03'] = { punishment = 'ban'},
	['prop_flag_columbia'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_o2_rail_a'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_o2_rail_b'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_o3_rail_a'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_o3_rail_b'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option1'] = { punishment = 'ban'},
	['proc_searock_01'] = { punishment = 'ban'},
	['apa_mp_h_yacht_'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option1_cola'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option2'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option2_cola'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option2_colb'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option3'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option3_cola'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option3_colb'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option3_colc'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option3_cold'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_option3_cole'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_jacuzzi_cam'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_jacuzzi_ripple003'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_jacuzzi_ripple1'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_jacuzzi_ripple2'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_radar_01a'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_win'] = { punishment = 'ban'},
	['prop_crashed_heli'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_door'] = { punishment = 'ban'},
	['prop_shamal_crash'] = { punishment = 'ban'},
	['xm_prop_x17_shamal_crash'] = { punishment = 'ban'},
	['apa_mp_apa_yacht_door2'] = { punishment = 'ban'},
	['apa_mp_apa_yacht'] = { punishment = 'ban'},
	['prop_flagpole_2b'] = { punishment = 'ban'},
	['prop_flagpole_2c'] = { punishment = 'ban'},
	['prop_flag_canada'] = { punishment = 'ban'},
	['apa_prop_yacht_float_1a'] = { punishment = 'ban'},
	['apa_prop_yacht_float_1b'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_01'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_02'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_03'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_04'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_05'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_06'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_07'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_08'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_09'] = { punishment = 'ban'},
	['apa_prop_yacht_glass_10'] = { punishment = 'ban'},
	['prop_flag_canada_s'] = { punishment = 'ban'},
	['prop_flag_eu'] = { punishment = 'ban'},
	['prop_flag_eu_s'] = { punishment = 'ban'},
	['prop_target_blue_arrow'] = { punishment = 'ban'},
	['prop_target_orange_arrow'] = { punishment = 'ban'},
	['prop_target_purp_arrow'] = { punishment = 'ban'},
	['prop_target_red_arrow'] = { punishment = 'ban'},
	['apa_prop_flag_argentina'] = { punishment = 'ban'},
	['apa_prop_flag_australia'] = { punishment = 'ban'},
	['apa_prop_flag_austria'] = { punishment = 'ban'},
	['apa_prop_flag_belgium'] = { punishment = 'ban'},
	['apa_prop_flag_brazil'] = { punishment = 'ban'},
	['apa_prop_flag_canadat_yt'] = { punishment = 'ban'},
	['apa_prop_flag_china'] = { punishment = 'ban'},
	['apa_prop_flag_columbia'] = { punishment = 'ban'},
	['apa_prop_flag_croatia'] = { punishment = 'ban'},
	['apa_prop_flag_czechrep'] = { punishment = 'ban'},
	['apa_prop_flag_denmark'] = { punishment = 'ban'},
	['apa_prop_flag_england'] = { punishment = 'ban'},
	['apa_prop_flag_eu_yt'] = { punishment = 'ban'},
	['apa_prop_flag_finland'] = { punishment = 'ban'},
	['apa_prop_flag_france'] = { punishment = 'ban'},
	['apa_prop_flag_german_yt'] = { punishment = 'ban'},
	['apa_prop_flag_hungary'] = { punishment = 'ban'},
	['apa_prop_flag_ireland'] = { punishment = 'ban'},
	['apa_prop_flag_israel'] = { punishment = 'ban'},
	['apa_prop_flag_italy'] = { punishment = 'ban'},
	['apa_prop_flag_jamaica'] = { punishment = 'ban'},
	['apa_prop_flag_japan_yt'] = { punishment = 'ban'},
	['apa_prop_flag_canada_yt'] = { punishment = 'ban'},
	['apa_prop_flag_lstein'] = { punishment = 'ban'},
	['apa_prop_flag_malta'] = { punishment = 'ban'},
	['apa_prop_flag_mexico_yt'] = { punishment = 'ban'},
	['apa_prop_flag_netherlands'] = { punishment = 'ban'},
	['apa_prop_flag_newzealand'] = { punishment = 'ban'},
	['apa_prop_flag_nigeria'] = { punishment = 'ban'},
	['apa_prop_flag_norway'] = { punishment = 'ban'},
	['apa_prop_flag_palestine'] = { punishment = 'ban'},
	['apa_prop_flag_poland'] = { punishment = 'ban'},
	['apa_prop_flag_portugal'] = { punishment = 'ban'},
	['apa_prop_flag_puertorico'] = { punishment = 'ban'},
	['apa_prop_flag_russia_yt'] = { punishment = 'ban'},
	['apa_prop_flag_scotland_yt'] = { punishment = 'ban'},
	['apa_prop_flag_script'] = { punishment = 'ban'},
	['apa_prop_flag_slovakia'] = { punishment = 'ban'},
	['apa_prop_flag_slovenia'] = { punishment = 'ban'},
	['apa_prop_flag_southafrica'] = { punishment = 'ban'},
	['apa_prop_flag_southkorea'] = { punishment = 'ban'},
	['apa_prop_flag_spain'] = { punishment = 'ban'},
	['apa_prop_flag_sweden'] = { punishment = 'ban'},
	['apa_prop_flag_switzerland'] = { punishment = 'ban'},
	['apa_prop_flag_turkey'] = { punishment = 'ban'},
	['apa_prop_flag_uk_yt'] = { punishment = 'ban'},
	['apa_prop_flag_us_yt'] = { punishment = 'ban'},
	['apa_prop_flag_wales'] = { punishment = 'ban'},
	['prop_flag_uk'] = { punishment = 'ban'},
	['prop_flag_uk_s'] = { punishment = 'ban'},
	['prop_flag_us'] = { punishment = 'ban'},
	['prop_flag_usboat'] = { punishment = 'ban'},
	['prop_flag_us_r'] = { punishment = 'ban'},
	['prop_flag_us_s'] = { punishment = 'ban'},
	['prop_flag_france'] = { punishment = 'ban'},
	['prop_flag_france_s'] = { punishment = 'ban'},
	['prop_flag_german'] = { punishment = 'ban'},
	['prop_flag_german_s'] = { punishment = 'ban'},
	['prop_flag_ireland'] = { punishment = 'ban'},
	['prop_flag_ireland_s'] = { punishment = 'ban'},
	['prop_flag_japan'] = { punishment = 'ban'},
	['prop_flag_japan_s'] = { punishment = 'ban'},
	['prop_flag_ls'] = { punishment = 'ban'},
	['prop_flag_lsfd'] = { punishment = 'ban'},
	['prop_flag_lsfd_s'] = { punishment = 'ban'},
	['prop_flag_lsservices'] = { punishment = 'ban'},
	['prop_flag_lsservices_s'] = { punishment = 'ban'},
	['prop_flag_ls_s'] = { punishment = 'ban'},
	['prop_flag_mexico'] = { punishment = 'ban'},
	['prop_flag_mexico_s'] = { punishment = 'ban'},
	['prop_flag_russia'] = { punishment = 'ban'},
	['prop_flag_russia_s'] = { punishment = 'ban'},
	['prop_flag_s'] = { punishment = 'ban'},
	['prop_flag_sa'] = { punishment = 'ban'},
	['prop_flag_sapd'] = { punishment = 'ban'},
	['prop_flag_sapd_s'] = { punishment = 'ban'},
	['prop_flag_sa_s'] = { punishment = 'ban'},
	['prop_flag_scotland'] = { punishment = 'ban'},
	['prop_flag_scotland_s'] = { punishment = 'ban'},
	['prop_flag_sheriff'] = { punishment = 'ban'},
	['prop_flag_sheriff_s'] = { punishment = 'ban'},
	['prop_flag_uk'] = { punishment = 'ban'},
	['prop_flag_uk_s'] = { punishment = 'ban'},
	['prop_flag_us'] = { punishment = 'ban'},
	['prop_flag_usboat'] = { punishment = 'ban'},
	['prop_flag_us_r'] = { punishment = 'ban'},
	['prop_flag_us_s'] = { punishment = 'ban'},
	['prop_flamingo'] = { punishment = 'ban'},
	['prop_swiss_ball_01'] = { punishment = 'ban'},
	['prop_air_bigradar_l1'] = { punishment = 'ban'},
	['prop_air_bigradar_l2'] = { punishment = 'ban'},
	['prop_air_bigradar_slod'] = { punishment = 'ban'},
	['p_fib_rubble_s'] = { punishment = 'ban'},
	['p_cs_mp_jet_01_s'] = { punishment = 'ban'},
	['prop_poly_bag_money'] = { punishment = 'ban'},
	['prop_air_radar_01'] = { punishment = 'ban'},
	['hei_prop_carrier_radar_1'] = { punishment = 'ban'},
	['prop_air_bigradar'] = { punishment = 'ban'},
	['prop_carrier_radar_1_l1'] = { punishment = 'ban'},
	['prop_asteroid_01'] = { punishment = 'ban'},
	['prop_xmas_ext'] = { punishment = 'ban'},
	['p_oil_pjack_01_amo'] = { punishment = 'ban'},
	['p_oil_pjack_01_s'] = { punishment = 'ban'},
	['p_oil_pjack_02_amo'] = { punishment = 'ban'},
	['p_oil_pjack_03_amo'] = { punishment = 'ban'},
	['p_oil_pjack_02_s'] = { punishment = 'ban'},
	['p_oil_pjack_03_s'] = { punishment = 'ban'},
	['prop_aircon_l_03'] = { punishment = 'ban'},
	['prop_med_jet_01'] = { punishment = 'ban'},
	['p_med_jet_01_s'] = { punishment = 'ban'},
	['hei_prop_carrier_jet'] = { punishment = 'ban'},
	['bkr_prop_biker_bblock_huge_01'] = { punishment = 'ban'},
	['bkr_prop_biker_bblock_huge_02'] = { punishment = 'ban'},
	['bkr_prop_biker_bblock_huge_04'] = { punishment = 'ban'},
	['bkr_prop_biker_bblock_huge_05'] = { punishment = 'ban'},
	['hei_prop_heist_emp'] = { punishment = 'ban'},
	['prop_weed_01'] = { punishment = 'ban'},
	['prop_air_bigradar'] = { punishment = 'ban'},
	['prop_lev_des_barge_02'] = { punishment = 'ban'},
	['hei_prop_carrier_defense_01'] = { punishment = 'ban'},
	['prop_aircon_m_04'] = { punishment = 'ban'},
	['prop_mp_ramp_03'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwuturn'] = { punishment = 'ban'},
	['ch3_12_animplane1_lod'] = { punishment = 'ban'},
	['ch3_12_animplane2_lod'] = { punishment = 'ban'},
	['hei_prop_hei_pic_pb_plane'] = { punishment = 'ban'},
	['light_plane_rig'] = { punishment = 'ban'},
	['prop_cs_plane_int_01'] = { punishment = 'ban'},
	['prop_dummy_plane'] = { punishment = 'ban'},
	['prop_mk_plane'] = { punishment = 'ban'},
	['v_44_planeticket'] = { punishment = 'ban'},
	['prop_planer_01'] = { punishment = 'ban'},
	['ch3_03_cliffrocks03b_lod'] = { punishment = 'ban'},
	['ch3_04_rock_lod_02'] = { punishment = 'ban'},
	['csx_coastsmalrock_01_'] = { punishment = 'ban'},
	['csx_coastsmalrock_02_'] = { punishment = 'ban'},
	['csx_coastsmalrock_03_'] = { punishment = 'ban'},
	['csx_coastsmalrock_04_'] = { punishment = 'ban'},
	['mp_player_introck'] = { punishment = 'ban'},
	['Heist_Yacht'] = { punishment = 'ban'},
	['csx_coastsmalrock_05_'] = { punishment = 'ban'},
	['mp_player_int_rock'] = { punishment = 'ban'},
	['mp_player_introck'] = { punishment = 'ban'},
	['prop_flagpole_1a'] = { punishment = 'ban'},
	['prop_flagpole_2a'] = { punishment = 'ban'},
	['prop_flagpole_3a'] = { punishment = 'ban'},
	['prop_a4_pile_01'] = { punishment = 'ban'},
	['cs2_10_sea_rocks_lod'] = { punishment = 'ban'},
	['cs2_11_sea_marina_xr_rocks_03_lod'] = { punishment = 'ban'},
	['prop_gold_cont_01'] = { punishment = 'ban'},
	['prop_hydro_platform'] = { punishment = 'ban'},
	['ch3_04_viewplatform_slod'] = { punishment = 'ban'},
	['ch2_03c_rnchstones_lod'] = { punishment = 'ban'},
	['proc_mntn_stone01'] = { punishment = 'ban'},
	['prop_beachflag_le'] = { punishment = 'ban'},
	['proc_mntn_stone02'] = { punishment = 'ban'},
	['cs2_10_sea_shipwreck_lod'] = { punishment = 'ban'},
	['des_shipsink_02'] = { punishment = 'ban'},
	['prop_dock_shippad'] = { punishment = 'ban'},
	['des_shipsink_03'] = { punishment = 'ban'},
	['des_shipsink_04'] = { punishment = 'ban'},
	['prop_mk_flag'] = { punishment = 'ban'},
	['prop_mk_flag_2'] = { punishment = 'ban'},
	['proc_mntn_stone03'] = { punishment = 'ban'},
	['FreeModeMale01'] = { punishment = 'ban'},
	['rsn_os_specialfloatymetal_n'] = { punishment = 'ban'},
	['rsn_os_specialfloatymetal'] = { punishment = 'ban'},
	['cs1_09_sea_ufo'] = { punishment = 'ban'},
	['rsn_os_specialfloaty2_light2'] = { punishment = 'ban'},
	['rsn_os_specialfloaty2_light'] = { punishment = 'ban'},
	['rsn_os_specialfloaty2'] = { punishment = 'ban'},
	['rsn_os_specialfloatymetal_n'] = { punishment = 'ban'},
	['rsn_os_specialfloatymetal'] = { punishment = 'ban'},
	['P_Spinning_Anus_S_Main'] = { punishment = 'ban'},
	['P_Spinning_Anus_S_Root'] = { punishment = 'ban'},
	['cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a'] = { punishment = 'ban'},
	['sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a'] = { punishment = 'ban'},
	['rnbj_wallsigns_0001'] = { punishment = 'ban'},
	['proc_sml_stones01'] = { punishment = 'ban'},
	['proc_sml_stones02'] = { punishment = 'ban'},
	['proc_sml_stones03'] = { punishment = 'ban'},
	['proc_stones_01'] = { punishment = 'ban'},
	['proc_stones_02'] = { punishment = 'ban'},
	['proc_stones_03'] = { punishment = 'ban'},
	['proc_stones_04'] = { punishment = 'ban'},
	['proc_stones_05'] = { punishment = 'ban'},
	['proc_stones_06'] = { punishment = 'ban'},
	['prop_coral_stone_03'] = { punishment = 'ban'},
	['prop_coral_stone_04'] = { punishment = 'ban'},
	['prop_gravestones_01a'] = { punishment = 'ban'},
	['prop_gravestones_02a'] = { punishment = 'ban'},
	['prop_gravestones_03a'] = { punishment = 'ban'},
	['prop_gravestones_04a'] = { punishment = 'ban'},
	['prop_gravestones_05a'] = { punishment = 'ban'},
	['prop_gravestones_06a'] = { punishment = 'ban'},
	['prop_gravestones_07a'] = { punishment = 'ban'},
	['prop_gravestones_08a'] = { punishment = 'ban'},
	['prop_gravestones_09a'] = { punishment = 'ban'},
	['prop_gravestones_10a'] = { punishment = 'ban'},
	['prop_prlg_gravestone_05a_l1'] = { punishment = 'ban'},
	['prop_prlg_gravestone_06a'] = { punishment = 'ban'},
	['test_prop_gravestones_04a'] = { punishment = 'ban'},
	['test_prop_gravestones_05a'] = { punishment = 'ban'},
	['test_prop_gravestones_07a'] = { punishment = 'ban'},
	['test_prop_gravestones_08a'] = { punishment = 'ban'},
	['test_prop_gravestones_09a'] = { punishment = 'ban'},
	['prop_prlg_gravestone_01a'] = { punishment = 'ban'},
	['prop_prlg_gravestone_02a'] = { punishment = 'ban'},
	['prop_prlg_gravestone_03a'] = { punishment = 'ban'},
	['prop_prlg_gravestone_04a'] = { punishment = 'ban'},
	['prop_stoneshroom1'] = { punishment = 'ban'},
	['prop_stoneshroom2'] = { punishment = 'ban'},
	['v_res_fa_stones01'] = { punishment = 'ban'},
	['test_prop_gravestones_01a'] = { punishment = 'ban'},
	['test_prop_gravestones_02a'] = { punishment = 'ban'},
	['prop_prlg_gravestone_05a'] = { punishment = 'ban'},
	['FreemodeFemale01'] = { punishment = 'ban'},
	['p_cablecar_s'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_l'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwuturn'] = { punishment = 'ban'},
	['p_spinning_anus_s'] = { punishment = 'ban'},
	['hei_prop_heist_tug'] = { punishment = 'ban'},
	['prop_air_bigradar'] = { punishment = 'ban'},
	['p_oil_slick_01'] = { punishment = 'ban'},
	['prop_dummy_01'] = { punishment = 'ban'},
	['hei_prop_heist_emp'] = { punishment = 'ban'},
	['p_tram_cash_s'] = { punishment = 'ban'},
	['hw1_blimp_ce2'] = { punishment = 'ban'},
	['prop_fire_exting_1a'] = { punishment = 'ban'},
	['prop_fire_exting_1b'] = { punishment = 'ban'},
	['prop_fire_exting_2a'] = { punishment = 'ban'},
	['prop_fire_exting_3a'] = { punishment = 'ban'},
	['hw1_blimp_ce2_lod'] = { punishment = 'ban'},
	['hw1_blimp_ce_lod'] = { punishment = 'ban'},
	['hw1_blimp_cpr003'] = { punishment = 'ban'},
	['hw1_blimp_cpr_null'] = { punishment = 'ban'},
	['hw1_blimp_cpr_null2'] = { punishment = 'ban'},
	['prop_lev_des_barage_02'] = { punishment = 'ban'},
	['hei_prop_carrier_defense_01'] = { punishment = 'ban'},
	['prop_juicestand'] = { punishment = 'ban'},
	['v_ilev_found_cranebucket'] = { punishment = 'ban'},
	['p_cs_sub_hook_01_s'] = { punishment = 'ban'},
	['hei_prop_heist_hook_01'] = { punishment = 'ban'},
	['prop_rope_hook_01'] = { punishment = 'ban'},
	['prop_sub_crane_hook'] = { punishment = 'ban'},
	['prop_vehicle_hook'] = { punishment = 'ban'},
	['prop_v_hook_s'] = { punishment = 'ban'},
	['prop_dock_crane_02_hook'] = { punishment = 'ban'},
	['prop_winch_hook_long'] = { punishment = 'ban'},
	['prop_coathook_01'] = { punishment = 'ban'},
	['prop_cs_sub_hook_01'] = { punishment = 'ban'},
	['prop_windmill_01'] = { punishment = 'ban'},
	['prop_Ld_ferris_wheel'] = { punishment = 'ban'},
	['p_tram_crash_s'] = { punishment = 'ban'},
	['p_oil_slick_01'] = { punishment = 'ban'},
	['p_ld_stinger_s'] = { punishment = 'ban'},
	['p_ld_soc_ball_01'] = { punishment = 'ban'},
	['p_parachute1_s'] = { punishment = 'ban'},
	['p_cablecar_s'] = { punishment = 'ban'},
	['prop_beach_fire'] = { punishment = 'ban'},
	['prop_lev_des_barge_02'] = { punishment = 'ban'},
	['prop_lev_des_barge_01'] = { punishment = 'ban'},
	['prop_sculpt_fix'] = { punishment = 'ban'},
	['prop_flagpole_2b'] = { punishment = 'ban'},
	['prop_flagpole_2c'] = { punishment = 'ban'},
	['prop_winch_hook_short'] = { punishment = 'ban'},
	['prop_flag_canada'] = { punishment = 'ban'},
	['prop_flag_canada_s'] = { punishment = 'ban'},
	['prop_flag_france'] = { punishment = 'ban'},
	['prop_flag_france_s'] = { punishment = 'ban'},
	['prop_flag_german'] = { punishment = 'ban'},
	['prop_ld_hook'] = { punishment = 'ban'},
	['prop_flag_german_s'] = { punishment = 'ban'},
	['prop_flag_ireland'] = { punishment = 'ban'},
	['prop_flag_ireland_s'] = { punishment = 'ban'},
	['prop_flag_japan'] = { punishment = 'ban'},
	['prop_flag_japan_s'] = { punishment = 'ban'},
	['prop_flag_ls'] = { punishment = 'ban'},
	['prop_flag_lsfd'] = { punishment = 'ban'},
	['prop_flag_lsfd_s'] = { punishment = 'ban'},
	['prop_cable_hook_01'] = { punishment = 'ban'},
	['prop_flag_lsservices'] = { punishment = 'ban'},
	['prop_flag_lsservices_s'] = { punishment = 'ban'},
	['prop_flag_ls_s'] = { punishment = 'ban'},
	['prop_flag_mexico'] = { punishment = 'ban'},
	['prop_flag_mexico_s'] = { punishment = 'ban'},
	['csx_coastboulder_00'] = { punishment = 'ban'},
	['des_tankercrash_01'] = { punishment = 'ban'},
	['des_tankerexplosion_01'] = { punishment = 'ban'},
	['des_tankerexplosion_02'] = { punishment = 'ban'},
	['des_trailerparka_02'] = { punishment = 'ban'},
	['des_trailerparkb_02'] = { punishment = 'ban'},
	['des_trailerparkc_02'] = { punishment = 'ban'},
	['des_trailerparkd_02'] = { punishment = 'ban'},
	['des_traincrash_root2'] = { punishment = 'ban'},
	['des_traincrash_root3'] = { punishment = 'ban'},
	['des_traincrash_root4'] = { punishment = 'ban'},
	['des_traincrash_root5'] = { punishment = 'ban'},
	['des_finale_vault_end'] = { punishment = 'ban'},
	['des_finale_vault_root001'] = { punishment = 'ban'},
	['des_finale_vault_root002'] = { punishment = 'ban'},
	['des_finale_vault_root003'] = { punishment = 'ban'},
	['des_finale_vault_root004'] = { punishment = 'ban'},
	['des_finale_vault_start'] = { punishment = 'ban'},
	['des_vaultdoor001_root001'] = { punishment = 'ban'},
	['des_vaultdoor001_root002'] = { punishment = 'ban'},
	['des_vaultdoor001_root003'] = { punishment = 'ban'},
	['des_vaultdoor001_root004'] = { punishment = 'ban'},
	['des_vaultdoor001_root005'] = { punishment = 'ban'},
	['des_vaultdoor001_root006'] = { punishment = 'ban'},
	['des_vaultdoor001_skin001'] = { punishment = 'ban'},
	['des_vaultdoor001_start'] = { punishment = 'ban'},
	['des_traincrash_root6'] = { punishment = 'ban'},
	['prop_ld_vault_door'] = { punishment = 'ban'},
	['prop_vault_door_scene'] = { punishment = 'ban'},
	['prop_vault_door_scene'] = { punishment = 'ban'},
	['prop_vault_shutter'] = { punishment = 'ban'},
	['p_fin_vaultdoor_s'] = { punishment = 'ban'},
	['v_ilev_bk_vaultdoor'] = { punishment = 'ban'},
	['prop_gold_vault_fence_l'] = { punishment = 'ban'},
	['prop_gold_vault_fence_r'] = { punishment = 'ban'},
	['prop_gold_vault_gate_01'] = { punishment = 'ban'},
	['prop_bank_vaultdoor'] = { punishment = 'ban'},
	['des_traincrash_root7'] = { punishment = 'ban'},
	['prop_flag_russia'] = { punishment = 'ban'},
	['prop_flag_russia_s'] = { punishment = 'ban'},
	['prop_flag_s'] = { punishment = 'ban'},
	['ch2_03c_props_rrlwindmill_lod'] = { punishment = 'ban'},
	['prop_flag_sa'] = { punishment = 'ban'},
	['prop_flag_sapd'] = { punishment = 'ban'},
	['prop_flag_sapd_s'] = { punishment = 'ban'},
	['prop_flag_sa_s'] = { punishment = 'ban'},
	['prop_flag_scotland'] = { punishment = 'ban'},
	['prop_flag_scotland_s'] = { punishment = 'ban'},
	['prop_flag_sheriff'] = { punishment = 'ban'},
	['prop_flag_sheriff_s'] = { punishment = 'ban'},
	['prop_flag_uk'] = { punishment = 'ban'},
	['prop_yacht_lounger'] = { punishment = 'ban'},
	['prop_yacht_seat_01'] = { punishment = 'ban'},
	['prop_yacht_seat_02'] = { punishment = 'ban'},
	['prop_yacht_seat_03'] = { punishment = 'ban'},
	['marina_xr_rocks_02'] = { punishment = 'ban'},
	['marina_xr_rocks_03'] = { punishment = 'ban'},
	['prop_test_rocks01'] = { punishment = 'ban'},
	['prop_test_rocks02'] = { punishment = 'ban'},
	['prop_test_rocks03'] = { punishment = 'ban'},
	['prop_test_rocks04'] = { punishment = 'ban'},
	['marina_xr_rocks_04'] = { punishment = 'ban'},
	['marina_xr_rocks_05'] = { punishment = 'ban'},
	['marina_xr_rocks_06'] = { punishment = 'ban'},
	['prop_yacht_table_01'] = { punishment = 'ban'},
	['csx_searocks_02'] = { punishment = 'ban'},
	['csx_searocks_03'] = { punishment = 'ban'},
	['csx_searocks_04'] = { punishment = 'ban'},
	['csx_searocks_05'] = { punishment = 'ban'},
	['csx_searocks_06'] = { punishment = 'ban'},
	['p_yacht_chair_01_s'] = { punishment = 'ban'},
	['p_yacht_sofa_01_s'] = { punishment = 'ban'},
	['prop_yacht_table_02'] = { punishment = 'ban'},
	['csx_coastboulder_00'] = { punishment = 'ban'},
	['csx_coastboulder_01'] = { punishment = 'ban'},
	['csx_coastboulder_02'] = { punishment = 'ban'},
	['csx_coastboulder_03'] = { punishment = 'ban'},
	['csx_coastboulder_04'] = { punishment = 'ban'},
	['csx_coastboulder_05'] = { punishment = 'ban'},
	['csx_coastboulder_06'] = { punishment = 'ban'},
	['csx_coastboulder_07'] = { punishment = 'ban'},
	['csx_coastrok1'] = { punishment = 'ban'},
	['csx_coastrok2'] = { punishment = 'ban'},
	['csx_coastrok3'] = { punishment = 'ban'},
	['csx_coastrok4'] = { punishment = 'ban'},
	['csx_coastsmalrock_01'] = { punishment = 'ban'},
	['csx_coastsmalrock_02'] = { punishment = 'ban'},
	['csx_coastsmalrock_03'] = { punishment = 'ban'},
	['csx_coastsmalrock_04'] = { punishment = 'ban'},
	['csx_coastsmalrock_05'] = { punishment = 'ban'},
	['prop_yacht_table_03'] = { punishment = 'ban'},
	['prop_flag_uk_s'] = { punishment = 'ban'},
	['prop_flag_us'] = { punishment = 'ban'},
	['prop_flag_usboat'] = { punishment = 'ban'},
	['prop_flag_us_r'] = { punishment = 'ban'},
	['prop_flag_us_s'] = { punishment = 'ban'},
	['p_gasmask_s'] = { punishment = 'ban'},
	['prop_flamingo'] = { punishment = 'ban'},
	['stt_prop_stunt_soccer_ball'] = { punishment = 'ban'},
	['prop_rock_4_big2'] = { punishment = 'ban'},
	['p_crahsed_heli_s'] = { punishment = 'ban'},
	['stt_prop_c4_stack'] = { punishment = 'ban'},
	['stt_prop_corner_sign_01'] = { punishment = 'ban'},
	['stt_prop_corner_sign_02'] = { punishment = 'ban'},
	['stt_prop_corner_sign_03'] = { punishment = 'ban'},
	['stt_prop_corner_sign_04'] = { punishment = 'ban'},
	['stt_prop_corner_sign_05'] = { punishment = 'ban'},
	['stt_prop_corner_sign_06'] = { punishment = 'ban'},
	['stt_prop_corner_sign_07'] = { punishment = 'ban'},
	['stt_prop_corner_sign_08'] = { punishment = 'ban'},
	['stt_prop_corner_sign_09'] = { punishment = 'ban'},
	['stt_prop_corner_sign_10'] = { punishment = 'ban'},
	['stt_prop_corner_sign_11'] = { punishment = 'ban'},
	['stt_prop_corner_sign_12'] = { punishment = 'ban'},
	['stt_prop_corner_sign_13'] = { punishment = 'ban'},
	['stt_prop_corner_sign_14'] = { punishment = 'ban'},
	['stt_prop_flagpole_1a'] = { punishment = 'ban'},
	['stt_prop_flagpole_1b'] = { punishment = 'ban'},
	['stt_prop_flagpole_1c'] = { punishment = 'ban'},
	['stt_prop_flagpole_1d'] = { punishment = 'ban'},
	['stt_prop_flagpole_1e'] = { punishment = 'ban'},
	['stt_prop_flagpole_1f'] = { punishment = 'ban'},
	['stt_prop_flagpole_2a'] = { punishment = 'ban'},
	['stt_prop_flagpole_2b'] = { punishment = 'ban'},
	['stt_prop_flagpole_2c'] = { punishment = 'ban'},
	['stt_prop_flagpole_2d'] = { punishment = 'ban'},
	['stt_prop_flagpole_2e'] = { punishment = 'ban'},
	['stt_prop_flagpole_2f'] = { punishment = 'ban'},
	['stt_prop_hoop_constraction_01a'] = { punishment = 'ban'},
	['stt_prop_hoop_small_01'] = { punishment = 'ban'},
	['stt_prop_hoop_tyre_01a'] = { punishment = 'ban'},
	['stt_prop_lives_bottle'] = { punishment = 'ban'},
	['stt_prop_race_gantry_01'] = { punishment = 'ban'},
	['stt_prop_race_start_line_01'] = { punishment = 'ban'},
	['stt_prop_race_start_line_01b'] = { punishment = 'ban'},
	['stt_prop_race_start_line_02'] = { punishment = 'ban'},
	['stt_prop_race_start_line_02b'] = { punishment = 'ban'},
	['stt_prop_race_start_line_03'] = { punishment = 'ban'},
	['stt_prop_race_start_line_03b'] = { punishment = 'ban'},
	['stt_prop_race_tannoy'] = { punishment = 'ban'},
	['stt_prop_ramp_adj_flip_m'] = { punishment = 'ban'},
	['stt_prop_ramp_adj_flip_mb'] = { punishment = 'ban'},
	['stt_prop_ramp_adj_flip_s'] = { punishment = 'ban'},
	['stt_prop_ramp_adj_flip_sb'] = { punishment = 'ban'},
	['stt_prop_ramp_adj_hloop'] = { punishment = 'ban'},
	['stt_prop_ramp_adj_loop'] = { punishment = 'ban'},
	['stt_prop_ramp_jump_l'] = { punishment = 'ban'},
	['stt_prop_ramp_jump_m'] = { punishment = 'ban'},
	['stt_prop_ramp_jump_s'] = { punishment = 'ban'},
	['stt_prop_ramp_jump_xl'] = { punishment = 'ban'},
	['stt_prop_ramp_jump_xs'] = { punishment = 'ban'},
	['stt_prop_ramp_jump_xxl'] = { punishment = 'ban'},
	['stt_prop_ramp_multi_loop_rb'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_l'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_l_l'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_l_m'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_l_s'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_l_xxl'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_m'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_s'] = { punishment = 'ban'},
	['stt_prop_ramp_spiral_xxl'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_01'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_02'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_03'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_04'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_05'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_06'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_07'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_08'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_09'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_10'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_11'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_11b'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_12'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_13'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_13b'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_14'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_14b'] = { punishment = 'ban'},
	['stt_prop_sign_circuit_15'] = { punishment = 'ban'},
	['stt_prop_slow_down'] = { punishment = 'ban'},
	['stt_prop_speakerstack_01a'] = { punishment = 'ban'},
	['stt_prop_startline_gantry'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_huge_01'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_huge_02'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_huge_03'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_huge_04'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_huge_05'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_hump_01'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_hump_02'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_lrg1'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_lrg2'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_lrg3'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_mdm1'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_mdm2'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_mdm3'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_qp'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_qp2'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_qp3'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_sml1'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_sml2'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_sml3'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_xl1'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_xl2'] = { punishment = 'ban'},
	['stt_prop_stunt_bblock_xl3'] = { punishment = 'ban'},
	['stt_prop_stunt_bowling_ball'] = { punishment = 'ban'},
	['stt_prop_stunt_bowling_pin'] = { punishment = 'ban'},
	['stt_prop_stunt_bowlpin_stand'] = { punishment = 'ban'},
	['stt_prop_stunt_domino'] = { punishment = 'ban'},
	['stt_prop_stunt_jump15'] = { punishment = 'ban'},
	['stt_prop_stunt_jump30'] = { punishment = 'ban'},
	['stt_prop_stunt_jump45'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_l'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_lb'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_loop'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_m'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_mb'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_s'] = { punishment = 'ban'},
	['stt_prop_stunt_jump_sb'] = { punishment = 'ban'},
	['stt_prop_stunt_landing_zone_01'] = { punishment = 'ban'},
	['stt_prop_stunt_ramp'] = { punishment = 'ban'},
	['stt_prop_stunt_soccer_ball'] = { punishment = 'ban'},
	['stt_prop_stunt_soccer_goal'] = { punishment = 'ban'},
	['stt_prop_stunt_soccer_lball'] = { punishment = 'ban'},
	['stt_prop_stunt_soccer_sball'] = { punishment = 'ban'},
	['stt_prop_stunt_target'] = { punishment = 'ban'},
	['stt_prop_stunt_target_small'] = { punishment = 'ban'},
	['stt_prop_stunt_track_bumps'] = { punishment = 'ban'},
	['stt_prop_stunt_track_cutout'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwlink'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwlink_02'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwsh15'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwshort'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwslope15'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwslope30'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwslope45'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwturn'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwuturn'] = { punishment = 'ban'},
	['stt_prop_stunt_track_exshort'] = { punishment = 'ban'},
	['stt_prop_stunt_track_fork'] = { punishment = 'ban'},
	['stt_prop_stunt_track_funlng'] = { punishment = 'ban'},
	['stt_prop_stunt_track_funnel'] = { punishment = 'ban'},
	['stt_prop_stunt_track_hill'] = { punishment = 'ban'},
	['stt_prop_stunt_track_hill2'] = { punishment = 'ban'},
	['stt_prop_stunt_track_jump'] = { punishment = 'ban'},
	['stt_prop_stunt_track_link'] = { punishment = 'ban'},
	['stt_prop_stunt_track_otake'] = { punishment = 'ban'},
	['stt_prop_stunt_track_sh15'] = { punishment = 'ban'},
	['stt_prop_stunt_track_sh30'] = { punishment = 'ban'},
	['stt_prop_stunt_track_sh45'] = { punishment = 'ban'},
	['stt_prop_stunt_track_sh45_a'] = { punishment = 'ban'},
	['stt_prop_stunt_track_short'] = { punishment = 'ban'},
	['stt_prop_stunt_track_slope15'] = { punishment = 'ban'},
	['stt_prop_stunt_track_slope30'] = { punishment = 'ban'},
	['stt_prop_stunt_track_slope45'] = { punishment = 'ban'},
	['stt_prop_stunt_track_start'] = { punishment = 'ban'},
	['stt_prop_stunt_track_start_02'] = { punishment = 'ban'},
	['stt_prop_stunt_track_straight'] = { punishment = 'ban'},
	['stt_prop_stunt_track_straightice'] = { punishment = 'ban'},
	['stt_prop_stunt_track_st_01'] = { punishment = 'ban'},
	['stt_prop_stunt_track_st_02'] = { punishment = 'ban'},
	['stt_prop_stunt_track_turn'] = { punishment = 'ban'},
	['stt_prop_stunt_track_turnice'] = { punishment = 'ban'},
	['stt_prop_stunt_track_uturn'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_crn'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_crn2'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_crn_15d'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_crn_30d'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_crn_5d'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_cross'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_end'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_ent'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_fn_01'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_fn_02'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_fn_03'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_fn_04'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_fn_05'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_fork'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_gap_01'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_gap_02'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_gap_03'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_hg'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_jmp'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_jmp2'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_l'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_m'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_qg'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_s'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_speed'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_speeda'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_speedb'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_xs'] = { punishment = 'ban'},
	['stt_prop_stunt_tube_xxs'] = { punishment = 'ban'},
	['stt_prop_stunt_wideramp'] = { punishment = 'ban'},
	['stt_prop_track_bend2_bar_l'] = { punishment = 'ban'},
	['stt_prop_track_bend2_bar_l_b'] = { punishment = 'ban'},
	['stt_prop_track_bend2_l'] = { punishment = 'ban'},
	['stt_prop_track_bend2_l_b'] = { punishment = 'ban'},
	['stt_prop_track_bend_15d'] = { punishment = 'ban'},
	['stt_prop_track_bend_15d_bar'] = { punishment = 'ban'},
	['stt_prop_track_bend_180d'] = { punishment = 'ban'},
	['stt_prop_track_bend_180d_bar'] = { punishment = 'ban'},
	['stt_prop_track_bend_30d'] = { punishment = 'ban'},
	['stt_prop_track_bend_30d_bar'] = { punishment = 'ban'},
	['stt_prop_track_bend_5d'] = { punishment = 'ban'},
	['stt_prop_track_bend_5d_bar'] = { punishment = 'ban'},
	['stt_prop_track_bend_bar_l'] = { punishment = 'ban'},
	['stt_prop_track_bend_bar_l_b'] = { punishment = 'ban'},
	['stt_prop_track_bend_bar_m'] = { punishment = 'ban'},
	['stt_prop_track_bend_l'] = { punishment = 'ban'},
	['stt_prop_track_bend_l_b'] = { punishment = 'ban'},
	['stt_prop_track_bend_m'] = { punishment = 'ban'},
	['stt_prop_track_block_01'] = { punishment = 'ban'},
	['stt_prop_track_block_02'] = { punishment = 'ban'},
	['stt_prop_track_block_03'] = { punishment = 'ban'},
	['stt_prop_track_chicane_l'] = { punishment = 'ban'},
	['stt_prop_track_chicane_l_02'] = { punishment = 'ban'},
	['stt_prop_track_chicane_r'] = { punishment = 'ban'},
	['stt_prop_track_chicane_r_02'] = { punishment = 'ban'},
	['stt_prop_track_cross'] = { punishment = 'ban'},
	['stt_prop_track_cross_bar'] = { punishment = 'ban'},
	['stt_prop_track_fork'] = { punishment = 'ban'},
	['stt_prop_track_fork_bar'] = { punishment = 'ban'},
	['stt_prop_track_funnel'] = { punishment = 'ban'},
	['stt_prop_track_funnel_ads_01a'] = { punishment = 'ban'},
	['stt_prop_track_funnel_ads_01b'] = { punishment = 'ban'},
	['stt_prop_track_funnel_ads_01c'] = { punishment = 'ban'},
	['stt_prop_track_jump_01a'] = { punishment = 'ban'},
	['stt_prop_track_jump_01b'] = { punishment = 'ban'},
	['stt_prop_track_jump_01c'] = { punishment = 'ban'},
	['stt_prop_track_jump_02a'] = { punishment = 'ban'},
	['stt_prop_track_jump_02b'] = { punishment = 'ban'},
	['stt_prop_track_jump_02c'] = { punishment = 'ban'},
	['stt_prop_track_link'] = { punishment = 'ban'},
	['stt_prop_track_slowdown'] = { punishment = 'ban'},
	['stt_prop_track_slowdown_t1'] = { punishment = 'ban'},
	['stt_prop_track_slowdown_t2'] = { punishment = 'ban'},
	['stt_prop_track_speedup'] = { punishment = 'ban'},
	['stt_prop_track_speedup_t1'] = { punishment = 'ban'},
	['stt_prop_track_speedup_t2'] = { punishment = 'ban'},
	['stt_prop_track_start'] = { punishment = 'ban'},
	['stt_prop_track_start_02'] = { punishment = 'ban'},
	['stt_prop_track_stop_sign'] = { punishment = 'ban'},
	['stt_prop_track_straight_bar_l'] = { punishment = 'ban'},
	['stt_prop_track_straight_bar_m'] = { punishment = 'ban'},
	['stt_prop_track_straight_bar_s'] = { punishment = 'ban'},
	['stt_prop_track_straight_l'] = { punishment = 'ban'},
	['stt_prop_track_straight_lm'] = { punishment = 'ban'},
	['stt_prop_track_straight_lm_bar'] = { punishment = 'ban'},
	['stt_prop_track_straight_m'] = { punishment = 'ban'},
	['stt_prop_track_straight_s'] = { punishment = 'ban'},
	['stt_prop_track_tube_01'] = { punishment = 'ban'},
	['stt_prop_track_tube_02'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_01'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_010'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_011'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_012'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_013'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_014'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_015'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_02'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_03'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_04'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_05'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_06'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_07'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_08'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_09'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l010'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l012'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l013'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l014'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l015'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l018'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l019'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l020'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l04'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l05'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l06'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l07'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l08'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l1'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l16'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l17'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l2'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0l3'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r010'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r011'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r012'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r013'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r014'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r015'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r016'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r017'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r018'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r019'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r04'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r05'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r06'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r07'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r08'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r09'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r1'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r2'] = { punishment = 'ban'},
	['stt_prop_tyre_wall_0r3'] = { punishment = 'ban'},
	['stt_prop_wallride_01'] = { punishment = 'ban'},
	['stt_prop_wallride_01b'] = { punishment = 'ban'},
	['stt_prop_wallride_02'] = { punishment = 'ban'},
	['stt_prop_wallride_02b'] = { punishment = 'ban'},
	['stt_prop_wallride_04'] = { punishment = 'ban'},
	['stt_prop_wallride_05'] = { punishment = 'ban'},
	['stt_prop_wallride_05b'] = { punishment = 'ban'},
	['stt_prop_wallride_45l'] = { punishment = 'ban'},
	['stt_prop_wallride_45la'] = { punishment = 'ban'},
	['stt_prop_wallride_45r'] = { punishment = 'ban'},
	['stt_prop_wallride_45ra'] = { punishment = 'ban'},
	['stt_prop_wallride_90l'] = { punishment = 'ban'},
	['stt_prop_wallride_90lb'] = { punishment = 'ban'},
	['stt_prop_wallride_90r'] = { punishment = 'ban'},
	['stt_prop_wallride_90rb'] = { punishment = 'ban'},
	['prop_fnclink_05crnr1'] = { punishment = 'ban'},
	['xs_prop_hamburgher_wl'] = { punishment = 'ban'},
	['xs_prop_plastic_bottle_wl'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwslope15'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwslope30'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwslope45'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwturn'] = { punishment = 'ban'},
	['stt_prop_stunt_track_fork'] = { punishment = 'ban'},
	['stt_prop_stunt_track_dwuturn'] = { punishment = 'ban'},
	['stt_prop_stunt_track_exshort'] = { punishment = 'ban'},
	['stt_prop_stunt_track_hill'] = { punishment = 'ban'},
	['stt_prop_stunt_track_funnel'] = { punishment = 'ban'},
	['stt_prop_stunt_track_funlng'] = { punishment = 'ban'},
	['prop_const_fence03b_cr'] = { punishment = 'ban'},
	['hei_prop_cash_crate_half_full'] = { punishment = 'ban'},
	['prop_mb_cargo_04b'] = { punishment = 'ban'},
	['prop_mb_crate_01a_set'] = { punishment = 'ban'},
	['prop_fire_hydrant_1'] = { punishment = 'ban'},
	['prop_fire_hydrant_2'] = { punishment = 'ban'},
	['prop_fire_hydrant_4'] = { punishment = 'ban'},
	['freight'] = { punishment = 'ban'},
	['stt_prop_race_start_line_03b'] = { punishment = 'ban'},
	['fib_5_mcs_10_lightrig'] = { punishment = 'ban'},
	['-1404869155'] = { punishment = 'ban'},

--[=================================== BLACKLISTED PEDS ================================]--

	['a_f_m_fatcult_01'] = {punishment = 'ban'}, --['kick', 'ban', 'ban' | (ban just blocks the ped from spawning without a kick or ban)]
	['a_f_y_topless_01'] = {punishment = 'ban'},
	['a_m_m_acult_01'] = {punishment = 'ban'},
	['a_m_m_hasjew_01'] = {punishment = 'ban'},
	['a_m_m_tranvest_01'] = {punishment = 'ban'},
	['a_m_o_acult_01'] = {punishment = 'ban'},
	['a_m_o_acult_02'] = {punishment = 'ban'},
	['a_m_o_beach_01'] = {punishment = 'ban'},
	['a_m_y_acult_01'] = {punishment = 'ban'},
	['a_m_y_acult_02'] = {punishment = 'ban'},
	['a_m_y_hasjew_01'] = {punishment = 'ban'},
	['a_m_y_motox_01'] = {punishment = 'ban'},
	['g_m_m_chemwork_01'] = {punishment = 'ban'},
	['g_m_m_chiboss_01'] = {punishment = 'ban'},
	['g_m_m_chicold_01'] = {punishment = 'ban'},
	['mp_f_cocaine_01'] = {punishment = 'ban'},
	['mp_f_deadhooker'] = {punishment = 'ban'},
	['mp_f_weed_01'] = {punishment = 'ban'},
	['mp_m_avongoon'] = {punishment = 'ban'},
	['mp_m_bogdangoon'] = {punishment = 'ban'},
	['mp_m_cocaine_01'] = {punishment = 'ban'},
	['mp_m_counterfeit_01'] = {punishment = 'ban'},
	['mp_m_fibsec_01'] = {punishment = 'ban'},
	['mp_m_exarmy_01'] = {punishment = 'ban'},
	['mp_m_forgery_01'] = {punishment = 'ban'},
	['mp_m_meth_01'] = {punishment = 'ban'},
	['mp_m_weapexp_01'] = {punishment = 'ban'},
	['mp_m_weapwork_01'] = {punishment = 'ban'},
	['mp_m_waremech_01'] = {punishment = 'ban'},
	['mp_m_weed_01'] = {punishment = 'ban'},
	['mp_s_m_armoured_01'] = {punishment = 'ban'},
	['s_f_y_factory_01'] = {punishment = 'ban'},
	['u_m_y_juggernaut_01'] = {punishment = 'ban'},
	['u_m_y_zombie_01'] = {punishment = 'ban'},
	['s_m_y_blackops_01'] = {punishment = 'ban'},
	['s_m_y_blackops_02'] = {punishment = 'ban'},
	['a_c_dolphin'] = {punishment = 'ban'},
	['a_c_humpback'] = {punishment = 'ban'},
	['a_c_killerwhale'] = {punishment = 'ban'},
	['a_c_cow'] = {punishment = 'ban'},
	['a_c_chimp'] = {punishment = 'ban'},
	['a_c_mtlion'] = {punishment = 'ban'},
	['a_c_rhesus'] = {punishment = 'ban'},
	['a_c_sharkhammer'] = {punishment = 'ban'},
	['a_c_sharktiger'] = {punishment = 'ban'},
	['a_c_stingray'] = {punishment = 'ban'},
	['cs_amandatownley'] = {punishment = 'ban'},
	['cs_andreas'] = {punishment = 'ban'},
	['cs_ashley'] = {punishment = 'ban'},
	['cs_bankman'] = {punishment = 'ban'},
	['cs_barry'] = {punishment = 'ban'},
	['cs_beverly'] = {punishment = 'ban'},
	['cs_brad'] = {punishment = 'ban'},
	['cs_bradcadaver'] = {punishment = 'ban'},
	['cs_carbuyer'] = {punishment = 'ban'},
	['cs_casey'] = {punishment = 'ban'},
	['cs_chengsr'] = {punishment = 'ban'},
	['cs_chrisformage'] = {punishment = 'ban'},
	['cs_clay'] = {punishment = 'ban'},
	['cs_dale'] = {punishment = 'ban'},
	['cs_davenorton'] = {punishment = 'ban'},
	['cs_debra'] = {punishment = 'ban'},
	['cs_denise'] = {punishment = 'ban'},
	['cs_devin'] = {punishment = 'ban'},
	['cs_dom'] = {punishment = 'ban'},
	['cs_dreyfuss'] = {punishment = 'ban'},
	['cs_drfriedlander'] = {punishment = 'ban'},
	['cs_fabien'] = {punishment = 'ban'},
	['cs_fbisuit_01'] = {punishment = 'ban'},
	['cs_floyd'] = {punishment = 'ban'},
	['cs_guadalope'] = {punishment = 'ban'},
	['cs_gurk'] = {punishment = 'ban'},
	['cs_hunter'] = {punishment = 'ban'},
	['cs_janet'] = {punishment = 'ban'},
	['cs_jewelass'] = {punishment = 'ban'},
	['cs_jimmyboston'] = {punishment = 'ban'},
	['cs_jimmydisanto'] = {punishment = 'ban'},
	['cs_joeminuteman'] = {punishment = 'ban'},
	['cs_johnnyklebitz'] = {punishment = 'ban'},
	['cs_josef'] = {punishment = 'ban'},
	['cs_josh'] = {punishment = 'ban'},
	['cs_karen_daniels'] = {punishment = 'ban'},
	['cs_lamardavis'] = {punishment = 'ban'},
	['cs_lazlow'] = {punishment = 'ban'},
	['cs_lazlow_2'] = {punishment = 'ban'},
	['cs_lestercrest'] = {punishment = 'ban'},
	['cs_lifeinvad_01'] = {punishment = 'ban'},
	['cs_magenta'] = {punishment = 'ban'},
	['cs_manuel'] = {punishment = 'ban'},
	['cs_marnie'] = {punishment = 'ban'},
	['cs_martinmadrazo'] = {punishment = 'ban'},
	['cs_maryann'] = {punishment = 'ban'},
	['cs_michelle'] = {punishment = 'ban'},
	['cs_milton'] = {punishment = 'ban'},
	['cs_molly'] = {punishment = 'ban'},
	['cs_movpremf_01'] = {punishment = 'ban'},
	['cs_movpremmale'] = {punishment = 'ban'},
	['cs_mrk'] = {punishment = 'ban'},
	['cs_mrs_thornhill'] = {punishment = 'ban'},
	['cs_mrsphillips'] = {punishment = 'ban'},
	['cs_natalia'] = {punishment = 'ban'},
	['cs_nervousron'] = {punishment = 'ban'},
	['cs_nigel'] = {punishment = 'ban'},
	['cs_old_man1a'] = {punishment = 'ban'},
	['cs_old_man2'] = {punishment = 'ban'},
	['cs_omega'] = {punishment = 'ban'},
	['cs_orleans'] = {punishment = 'ban'},
	['cs_paper'] = {punishment = 'ban'},
	['cs_patricia'] = {punishment = 'ban'},
	['cs_priest'] = {punishment = 'ban'},
	['cs_prolsec_02'] = {punishment = 'ban'},
	['cs_russiandrunk'] = {punishment = 'ban'},
	['cs_siemonyetarian'] = {punishment = 'ban'},
	['cs_solomon'] = {punishment = 'ban'},
	['cs_stevehains'] = {punishment = 'ban'},
	['cs_stretch'] = {punishment = 'ban'},
	['cs_tanisha'] = {punishment = 'ban'},
	['cs_taocheng'] = {punishment = 'ban'},
	['cs_taostranslator'] = {punishment = 'ban'},
	['cs_tenniscoach'] = {punishment = 'ban'},
	['cs_terry'] = {punishment = 'ban'},
	['cs_tom'] = {punishment = 'ban'},
	['cs_tomepsilon'] = {punishment = 'ban'},
	['cs_tracydisanto'] = {punishment = 'ban'},
	['cs_wade'] = {punishment = 'ban'},
	['cs_zimbor'] = {punishment = 'ban'},
	['csb_abigail'] = {punishment = 'ban'},
	['csb_agent'] = {punishment = 'ban'},
	['csb_alan'] = {punishment = 'ban'},
	['csb_anita'] = {punishment = 'ban'},
	['csb_anton'] = {punishment = 'ban'},
	['csb_avon'] = {punishment = 'ban'},
	['csb_ballasog'] = {punishment = 'ban'},
	['csb_bogdan'] = {punishment = 'ban'},
	['csb_bride'] = {punishment = 'ban'},
	['csb_bryony'] = {punishment = 'ban'},
	['csb_burgerdrug'] = {punishment = 'ban'},
	['csb_car3guy1'] = {punishment = 'ban'},
	['csb_car3guy2'] = {punishment = 'ban'},
	['csb_chef'] = {punishment = 'ban'},
	['csb_chef2'] = {punishment = 'ban'},
	['csb_chin_goon'] = {punishment = 'ban'},
	['csb_cletus'] = {punishment = 'ban'},
	['csb_cop'] = {punishment = 'ban'},
	['csb_customer'] = {punishment = 'ban'},
	['csb_denise_friend'] = {punishment = 'ban'},
	['csb_dix'] = {punishment = 'ban'},
	['csb_djblamadon'] = {punishment = 'ban'},
	['csb_englishdave'] = {punishment = 'ban'},
	['csb_fos_rep'] = {punishment = 'ban'},
	['csb_g'] = {punishment = 'ban'},
	['csb_groom'] = {punishment = 'ban'},
	['csb_grove_str_dlr'] = {punishment = 'ban'},
	['csb_hao'] = {punishment = 'ban'},
	['csb_hugh'] = {punishment = 'ban'},
	['csb_imran'] = {punishment = 'ban'},
	['csb_jackhowitzer'] = {punishment = 'ban'},
	['csb_janitor'] = {punishment = 'ban'},
	['csb_maude'] = {punishment = 'ban'},
	['csb_money'] = {punishment = 'ban'},
	['csb_mp_agent14'] = {punishment = 'ban'},
	['csb_mrs_r'] = {punishment = 'ban'},
	['csb_mweather'] = {punishment = 'ban'},
	['csb_ortega'] = {punishment = 'ban'},
	['csb_oscar'] = {punishment = 'ban'},
	['csb_paige'] = {punishment = 'ban'},
	['csb_popov'] = {punishment = 'ban'},
	['csb_porndudes'] = {punishment = 'ban'},
	['csb_prologuedriver'] = {punishment = 'ban'},
	['csb_prolsec'] = {punishment = 'ban'},
	['csb_ramp_gang'] = {punishment = 'ban'},
	['csb_ramp_hic'] = {punishment = 'ban'},
	['csb_ramp_hipster'] = {punishment = 'ban'},
	['csb_ramp_marine'] = {punishment = 'ban'},
	['csb_ramp_mex'] = {punishment = 'ban'},
	['csb_rashcosvki'] = {punishment = 'ban'},
	['csb_reporter'] = {punishment = 'ban'},
	['csb_roccopelosi'] = {punishment = 'ban'},
	['csb_screen_writer'] = {punishment = 'ban'},
	['csb_sol'] = {punishment = 'ban'},
	['csb_stripper_01'] = {punishment = 'ban'},
	['csb_stripper_02'] = {punishment = 'ban'},
	['csb_talcc'] = {punishment = 'ban'},
	['csb_talmm'] = {punishment = 'ban'},
	['csb_tonya'] = {punishment = 'ban'},
	['csb_tonyprince'] = {punishment = 'ban'},
	['csb_trafficwarden'] = {punishment = 'ban'},
	['csb_undercover'] = {punishment = 'ban'},
	['csb_vagspeak'] = {punishment = 'ban'},
	['csb_agatha'] = {punishment = 'ban'},
	['csb_avery'] = {punishment = 'ban'},
	['csb_brucie2'] = {punishment = 'ban'},
	['csb_thornton'] = {punishment = 'ban'},
	['csb_tomcasino'] = {punishment = 'ban'},
	['csb_vincent'] = {punishment = 'ban'},

                             
--[=================================== BLACKLISTED VEHICLES ===================================]--

    ['adder'] = {punishment = 'ban'}, --['kick', 'ban', 'ban' | (ban blocks the vehicle from spawning without a kick or ban)]
	['metrotrain'] = {punishment = 'ban'},
	['scramjet'] = {punishment = 'kick'},
	['strikeforce'] = {punishment = 'kick'},
	['terbyte'] = {punishment = 'ban'},
	['bruiser'] = {punishment = 'ban'},
	['bruiser2'] = {punishment = 'ban'},
	['bruiser3'] = {punishment = 'ban'},
	['brutus'] = {punishment = 'ban'},
	['brutus2'] = {punishment = 'ban'},
	['brutus3'] = {punishment = 'ban'},
	['cerberus'] = {punishment = 'ban'},
	['cerberus2'] = {punishment = 'ban'},
	['cerberus3'] = {punishment = 'ban'},
	['deathbike'] = {punishment = 'ban'},
	['deathbike2'] = {punishment = 'ban'},
	['deathbike3'] = {punishment = 'ban'},
	['dominator4'] = {punishment = 'ban'},
	['dominator5'] = {punishment = 'ban'},
	['dominator6'] = {punishment = 'ban'},
	['impaler2'] = {punishment = 'ban'},
	['impaler3'] = {punishment = 'ban'},
	['impaler4'] = {punishment = 'ban'},
	['imperator'] = {punishment = 'ban'},
	['imperator2'] = {punishment = 'ban'},
	['imperator3'] = {punishment = 'ban'},
	['issi4'] = {punishment = 'ban'},
	['issi5'] = {punishment = 'ban'},
	['issi6'] = {punishment = 'ban'},
	['monster3'] = {punishment = 'kick'},
	['monster4'] = {punishment = 'kick'},
	['monster5'] = {punishment = 'kick'},
	['scarab'] = {punishment = 'ban'},
	['scarab2'] = {punishment = 'ban'},
	['scarab3'] = {punishment = 'ban'},
	['slamvan4'] = {punishment = 'ban'},
	['slamvan5'] = {punishment = 'ban'},
	['slamvan6'] = {punishment = 'ban'},
	['zr380'] = {punishment = 'ban'},
	['zr3802'] = {punishment = 'ban'},
	['zr3803'] = {punishment = 'ban'},
	['scarab3'] = {punishment = 'ban'},
	['cargoPlane'] = {punishment = 'ban'},
	['submersible'] = {punishment = 'ban'},
	['submersible2'] = {punishment = 'ban'},
	['tug'] = {punishment = 'ban'},
	['biff'] = {punishment = 'ban'},
	['hauler2'] = {punishment = 'ban'},
	['phantom2'] = {punishment = 'ban'},
	['phantom3'] = {punishment = 'ban'},
	['stockade3'] = {punishment = 'ban'},
	['pBus'] = {punishment = 'ban'},
	['fireTruk'] = {punishment = 'none'},
	['policeOld1'] = {punishment = 'ban'},
	['policeOld2'] = {punishment = 'ban'},
	['predator'] = {punishment = 'ban'},
	['annihilator'] = {punishment = 'ban'},
	['buzzard'] = {punishment = 'ban'},
	['buzzard2'] = {punishment = 'ban'},
	['cargobob'] = {punishment = 'ban'},
	['cargobob2'] = {punishment = 'ban'},
	['cargobob3'] = {punishment = 'ban'},
	['cargobob4'] = {punishment = 'ban'},
	['savage'] = {punishment = 'ban'},
	['skylift'] = {punishment = 'ban'},
	['supervolito'] = {punishment = 'ban'},
	['supervolito2'] = {punishment = 'ban'},
	['swift'] = {punishment = 'ban'},
	['swift2'] = {punishment = 'ban'},
	['valkyrie'] = {punishment = 'ban'},
	['valkyrie2'] = {punishment = 'ban'},
	['volatus'] = {punishment = 'ban'},
	['bulldozer'] = {punishment = 'ban'},
	['dump'] = {punishment = 'ban'},
	['handler'] = {punishment = 'ban'},
	['mixer'] = {punishment = 'ban'},
	['mixer2'] = {punishment = 'ban'},
	['rubble'] = {punishment = 'ban'},
	['tiptruck'] = {punishment = 'ban'},
	['tiptruck2'] = {punishment = 'ban'},
	['apc'] = {punishment = 'ban'},
	['barracks'] = {punishment = 'ban'},
	['barracks2'] = {punishment = 'ban'},
	['barracks3'] = {punishment = 'ban'},
	['halftrack'] = {punishment = 'ban'},
	['rhino'] = {punishment = 'ban'},
	['trailersmall2'] = {punishment = 'ban'},
	['oppressor'] = {punishment = 'ban'},
	['oppressor2'] = {punishment = 'ban'},
	['ratbike'] = {punishment = 'ban'},
	['sanctus'] = {punishment = 'ban'},
	['shotaro'] = {punishment = 'ban'},
	['vindicator'] = {punishment = 'ban'},
	['thrust'] = {punishment = 'ban'},
	['vader'] = {punishment = 'ban'},
	['vortex'] = {punishment = 'ban'},
	['wolfsbane'] = {punishment = 'ban'},
	['zombiea'] = {punishment = 'ban'},
	['zombieb'] = {punishment = 'ban'},
	['dukes2'] = {punishment = 'ban'},
	['lurcher'] = {punishment = 'ban'},
	['ruiner2'] = {punishment = 'ban'},
	['sadler2'] = {punishment = 'ban'},
	['slamvan2'] = {punishment = 'ban'},
	['slamvan3'] = {punishment = 'ban'},
	['tampa3'] = {punishment = 'ban'},
	['blazer5'] = {punishment = 'ban'},
	['dune2'] = {punishment = 'ban'},
	['dune3'] = {punishment = 'ban'},
	['dune4'] = {punishment = 'ban'},
	['dune5'] = {punishment = 'ban'},
	['insurgent'] = {punishment = 'ban'},
	['insurgent2'] = {punishment = 'ban'},
	['insurgent3'] = {punishment = 'ban'},
	['marshall'] = {punishment = 'ban'},
	['mesa2'] = {punishment = 'ban'},
	['monster'] = {punishment = 'ban'},
	['nightshark'] = {punishment = 'ban'},
	['rancherXL2'] = {punishment = 'ban'},
	['technical'] = {punishment = 'ban'},
	['technical2'] = {punishment = 'ban'},
	['technical3'] = {punishment = 'ban'},
	['trophyTruck'] = {punishment = 'ban'},
	['trophyTruck2'] = {punishment = 'ban'},
	['besra'] = {punishment = 'ban'},
	['blimp'] = {punishment = 'ban'},
	['blimp2'] = {punishment = 'ban'},
	['cuban800'] = {punishment = 'ban'},
	['dodo'] = {punishment = 'ban'},
	['duster'] = {punishment = 'ban'},
	['hydra'] = {punishment = 'ban'},
	['jet'] = {punishment = 'ban'},
	['lazer'] = {punishment = 'ban'},
	['luxor'] = {punishment = 'ban'},
	['luxor2'] = {punishment = 'ban'},
	['mammatus'] = {punishment = 'ban'},
	['miljet'] = {punishment = 'ban'},
	['nimbus'] = {punishment = 'ban'},
	['shamal'] = {punishment = 'ban'},
	['stunt'] = {punishment = 'ban'},
	['titan'] = {punishment = 'ban'},
	['velum'] = {punishment = 'ban'},
	['velum2'] = {punishment = 'ban'},
	['vestra'] = {punishment = 'ban'},
	['baller3'] = {punishment = 'ban'},
	['baller4'] = {punishment = 'ban'},
	['baller5'] = {punishment = 'ban'},
	['baller6'] = {punishment = 'ban'},
	['asea2'] = {punishment = 'ban'},
	['cog552'] = {punishment = 'ban'},
	['cog55'] = {punishment = 'ban'},
	['cognoscenti2'] = {punishment = 'ban'},
	['emperor3'] = {punishment = 'ban'},
	['limo2'] = {punishment = 'ban'},
	['airbus'] = {punishment = 'ban'},
	['brickade'] = {punishment = 'ban'},
	['bus'] = {punishment = 'ban'},
	['coach'] = {punishment = 'ban'},
	['rallytruck'] = {punishment = 'ban'},
	['rentalBus'] = {punishment = 'ban'},
	['tourbus'] = {punishment = 'ban'},
	['trash'] = {punishment = 'ban'},
	['trash2'] = {punishment = 'ban'},
	['comet3'] = {punishment = 'ban'},
	['kuruma2'] = {punishment = 'ban'},
	['raptor'] = {punishment = 'ban'},
	['ruston'] = {punishment = 'ban'},
	['schafter3'] = {punishment = 'ban'},
	['schafter4'] = {punishment = 'ban'},
	['schafter5'] = {punishment = 'ban'},
	['schafter6'] = {punishment = 'ban'},
	['armytanker'] = {punishment = 'ban'},
	['armytrailer'] = {punishment = 'ban'},
	['armytrailer2'] = {punishment = 'ban'},
	['baletrailer'] = {punishment = 'ban'},
	['cablecar'] = {punishment = 'ban'},
	['docktrailer'] = {punishment = 'ban'},
	['graintrailer'] = {punishment = 'ban'},
	['proptrailer'] = {punishment = 'ban'},
	['raketrailer'] = {punishment = 'ban'},
	['tr2'] = {punishment = 'ban'},
	['tr3'] = {punishment = 'ban'},
	['tr4'] = {punishment = 'ban'},
	['trflat'] = {punishment = 'ban'},
	['tvtrailer'] = {punishment = 'ban'},
	['tanker'] = {punishment = 'ban'},
	['tanker2'] = {punishment = 'ban'},
	['trailerlogs'] = {punishment = 'ban'},
	['trailers'] = {punishment = 'ban'},
	['trailers2'] = {punishment = 'ban'},
	['freight'] = {punishment = 'ban'},
	['freightcar'] = {punishment = 'ban'},
	['freightcont1'] = {punishment = 'ban'},
	['freightcont2'] = {punishment = 'ban'},
	['freightgrain'] = {punishment = 'ban'},
	['freighttrailer'] = {punishment = 'ban'},
	['tankercar'] = {punishment = 'ban'},
	['caddy3'] = {punishment = 'ban'},
	['docktug'] = {punishment = 'ban'},
	['forklift'] = {punishment = 'ban'},
	['ripley'] = {punishment = 'ban'},
	['scrap'] = {punishment = 'ban'},
	['tractor'] = {punishment = 'ban'},
	['tractor3'] = {punishment = 'ban'},
	['tractor2'] = {punishment = 'ban'},
	['trailerlarge'] = {punishment = 'ban'},
	['trailerS4'] = {punishment = 'ban'},
	['utillitruck'] = {punishment = 'ban'},
	['utillitruck3'] = {punishment = 'ban'},
	['utilliTruck2'] = {punishment = 'ban'},
	['boxville5'] = {punishment = 'ban'},
	['burrito5'] = {punishment = 'ban'},
	['speedo2'] = {punishment = 'ban'},
	['voltic2'] = {punishment = 'ban'},
	['boxville5'] = {punishment = 'ban'},
	['wastelander'] = {punishment = 'ban'},
	['fcr'] = {punishment = 'ban'},
	['fcr2'] = {punishment = 'ban'},
	['ruiner3'] = {punishment = 'ban'},
	['ruston'] = {punishment = 'ban'},
	['alphaz1'] = {punishment = 'ban'},
	['starling'] = {punishment = 'ban'},
	['tula'] = {punishment = 'ban'},
	['havok'] = {punishment = 'ban'},
	['microlight'] = {punishment = 'ban'},
	['molotok'] = {punishment = 'ban'},
	['rogue'] = {punishment = 'ban'},
	['howard'] = {punishment = 'ban'},
	['pyro'] = {punishment = 'ban'},
	['hunter'] = {punishment = 'ban'},
	['mogul'] = {punishment = 'ban'},
	['bombushka'] = {punishment = 'ban'},
	['vigilante'] = {punishment = 'ban'},
	['seabreeze'] = {punishment = 'ban'},
	['akula'] = {punishment = 'ban'},
	['barrage'] = {punishment = 'ban'},
	['chernobog'] = {punishment = 'ban'},
	['raiden'] = {punishment = 'ban'},
	['yosemite'] = {punishment = 'ban'},
	['deluxo'] = {punishment = 'ban'},
	['avenger'] = {punishment = 'ban'},
	['avenger2'] = {punishment = 'ban'},
	['thruster'] = {punishment = 'ban'},
	['pariah'] = {punishment = 'ban'},
	['stromberg'] = {punishment = 'ban'},
	['comet4'] = {punishment = 'ban'},
	['riot2'] = {punishment = 'ban'},
	['khanjali'] = {punishment = 'ban'},
	['volatol'] = {punishment = 'ban'},
	['caracara'] = {punishment = 'ban'},
	['seasparrow'] = {punishment = 'ban'},
	['blimp3'] = {punishment = 'ban'},
	['menacer'] = {punishment = 'ban'},
	['freecrawler'] = {punishment = 'ban'},
	['mule4'] = {punishment = 'ban'},
	['patriot2'] = {punishment = 'ban'},
	['pbus2'] = {punishment = 'ban'},
	['pounder2'] = {punishment = 'ban'},
	['paragon2'] = {punishment = 'ban'},
	['rrocket'] = {punishment = 'ban'},
	['trailers3'] = {punishment = 'ban'}
}

FAC.Weapons = {
	["WEAPON_DAGGER"] = {label = "Antique Cavalry Dagger", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_BAT"] = {label = "Baseball Bat", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_BOTTLE"] = {label = "Broken Bottle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_CROWBAR"] = {label = "Crowbar", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_FLASHLIGHT"] = {label = "Flashlight", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_GOLFCLUB"] = {label = "Golf Club", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_HAMMER"] = {label = "Hammer", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_HATCHET"] = {label = "Hatchet", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_KNUCKLE"] = {label = "Brass Knuckles", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_KNIFE"] = {label = "Knife", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_MACHETE"] = {label = "Machete", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SWITCHBLADE"] = {label = "Switchblade", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_NIGHTSTICK"] = {label = "Nightstick", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_WRENCH"] = {label = "Pipe Wrench", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_BATTLEAXE"] = {label = "Battle Axe", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_POOLCUE"] = {label = "Pool Cue", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_STONE_HATCHET"] = {label = "Stone Hatchet", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_PISTOL"] = {label = "Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_PISTOL_MK2"] = {label = "Pistol Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_COMBATPISTOL"] = {label = "Combat Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_PISTOL50"] = {label = "Pistol .50", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SNSPISTOL"] = {label = "SNS Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SNSPISTOL_MK2"] = {label = "SNS Pistol Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_HEAVYPISTOL"] = {label = "Heavy Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_VINTAGEPISTOL"] = {label = "Vintage Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_FLAREGUN"] = {label = "Flare Gun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_MARKSMANPISTOL"] = {label = "Marksman Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_REVOLVER"] = {label = "Heavy Revolver", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_REVOLVER_MK2"] = {label = "Heavy Revolver Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_DOUBLEACTION"] = {label = "Double Action Revolver", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_RAYPISTOL"] = {label = "Up-n-Atomizer", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_CERAMICPISTOL"] = {label = "Ceramic Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_NAVYREVOLVER"] = {label = "Navy Revolver", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_GADGETPISTOL"] = {label = "Perico Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_MICROSMG"] = {label = "Micro SMG", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SMG"] = {label = "SMG", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SMG_MK2"] = {label = "SMG Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_ASSAULTSMG"] = {label = "Assault SMG", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_COMBATPDW"] = {label = "Combat PDW", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_MACHINEPISTOL"] = {label = "Machine Pistol", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_MINISMG"] = {label = "Mini SMG", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_RAYCARBINE"] = {label = "Unholy Hellbringer", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_PUMPSHOTGUN"] = {label = "Pump Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_PUMPSHOTGUN_MK2"] = {label = "Pump Shotgun Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_SAWNOFFSHOTGUN"] = {label = "Sawed-Off Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_ASSAULTSHOTGUN"] = {label = "Assault Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_BULLPUPSHOTGUN"] = {label = "Bullpup Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_MUSKET"] = {label = "Musket", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_HEAVYSHOTGUN"] = {label = "Heavy Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_DBSHOTGUN"] = {label = "Double Barrel Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_AUTOSHOTGUN"] = {label = "Sweeper Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_COMBATSHOTGUN"] = {label = "Combat Shotgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_ASSAULTRIFLE"] = {label = "Assault Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_ASSAULTRIFLE_MK2"] = {label = "Assault Rifle Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_CARBINERIFLE"] = {label = "Carbine Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_CARBINERIFLE_MK2"] = {label = "Carbine Rifle Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_ADVANCEDRIFLE"] = {label = "Advanced Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SPECIALCARBINE"] = {label = "Special Carbine", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SPECIALCARBINE_MK2"] = {label = "Special Carbine Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_BULLPUPRIFLE"] = {label = "Bullpup Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_BULLPUPRIFLE_MK2"] = {label = "Bullpup Rifle Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_COMPACTRIFLE"] = {label = "Compact Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_MILITARYRIFLE"] = {label = "Military Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_MG"] = {label = "MG", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_COMBATMG"] = {label = "Combat MG", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_COMBATMG_MK2"] = {label = "Combat MG Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_GUSENBERG"] = {label = "Gusenberg Sweeper", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_SNIPERRIFLE"] = {label = "Sniper Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_HEAVYSNIPER"] = {label = "Heavy Sniper", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'kick'},
	["WEAPON_HEAVYSNIPER_MK2"] = {label = "Heavy Sniper Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'kick'},
	["WEAPON_MARKSMANRIFLE"] = {label = "Marksman Rifle", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_MARKSMANRIFLE_MK2"] = {label = "Marksman Rifle Mk II", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_RPG"] = {label = "RPG", maxAmmo = 20, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_GRENADELAUNCHER"] = {label = "Grenade Launcher", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_GRENADELAUNCHER_SMOKE"] = {label = "Grenade Launcher Smoke", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = false, punishment = 'ban'},
	["WEAPON_MINIGUN"] = {label = "Minigun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_FIREWORK"] = {label = "Firework Launcher", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_RAILGUN"] = {label = "Railgun", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_HOMINGLAUNCHER"] = {label = "Homing Launcher", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_COMPACTLAUNCHER"] = {label = "Compact Grenade Launcher", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_RAYMINIGUN"] = {label = "Widowmaker", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_GRENADE"] = {label = "Grenade", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_BZGAS"] = {label = "BZ Gas", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_MOLOTOV"] = {label = "Molotov Cocktail", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_STICKYBOMB"] = {label = "Sticky Bomb", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_PROXMINE"] = {label = "Proximity Mines", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_SNOWBALL"] = {label = "Snowballs", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_PIPEBOMB"] = {label = "Pipe Bombs", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_BALL"] = {label = "Baseball", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_SMOKEGRENADE"] = {label = "Tear Gas", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_FLARE"] = {label = "Flare", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_PETROLCAN"] = {label = "Jerry Can", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["GADGET_PARACHUTE"] = {label = "Parachute", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_FIREEXTINGUISHER"] = {label = "Fire Extinguisher", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'},
	["WEAPON_HAZARDCAN"] = {label = "Hazardous Jerry Can", maxAmmo = 250, damageMultiplier = 1000.0, blacklisted = true, punishment = 'ban'}
}

FAC.Explosions = {
	[0] = {label = "Grenade"},
	[1] = {label = "Grenade Launcher"},
	[2] = {label = "Sticky Bomb"},
	[3] = {label = "Molotov"},
	[4] = {label = "Rocket"},
	[5] = {label = "Tank Shell"},
	[6] = {label = "Hi Octane"},
	[8] = {label = "Plane"},
	[10] = {label = "Bike"},
	[11] = {label = "Steam"},
	[12] = {label = "Flame"},
	[13] = {label = "Water Hydrant"},
	[14] = {label = "Gas Canister"},
	[15] = {label = "Boat"},
	[16] = {label = "Destroyed Ship"},
	[17] = {label = "Truck"},
	[18] = {label = "Bullet"},
	[19] = {label = "Smoke Grenade Launcher"},
	[20] = {label = "Smoke Grenade"},
	[21] = {label = "BZ Gas"},
	[22] = {label = "Flare"},
	[23] = {label = "Gas Canister"},
	[24] = {label = "Extinguisher"},
	[25] = {label = "Programmablear"},
	[26] = {label = "Train"},
	[27] = {label = "Barrel"},
	[28] = {label = "Propane"},
	[29] = {label = "Blimp"},
	[30] = {label = "Gas Tank Explosion"},
	[31] = {label = "Tanker"},
	[32] = {label = "Plane Rocket"},
	[33] = {label = "Vehicle Bullet"},
	[34] = {label = "Gas Tank"},
	[35] = {label = "Bird Crap"},
	[36] = {label = "Railgun"},
	[37] = {label = "Blimp 2"},
	[38] = {label = "Firework"},
	[39] = {label = "Snowball"},
	[40] = {label = "Proximity Mine"},
	[41] = {label = "Valkyrie Cannon"},
	[42] = {label = "Air Defense"},
	[43] = {label = "Pipe Bomb"},
	[44] = {label = "Vehicle Mine"},
	[45] = {label = "Explosive Ammo"},
	[46] = {label = "APC Shell"},
	[47] = {label = "Bomb: Cluster"},
	[48] = {label = "Bomb: Gas"},
	[49] = {label = "Bomb: Incendiary"},
	[50] = {label = "Bomb: Standard"},
	[51] = {label = "Torpedo"},
	[52] = {label = "Underwater Torpedo"},
	[53] = {label = "Bombushka Cannon Gas"},
	[54] = {label = "Bomb Cluster Secondary"},
	[55] = {label = "Hunter Barrage"},
	[56] = {label = "Hunter Cannon"},
	[57] = {label = "Rogue Cannon"},
	[58] = {label = "Underwater Mine"},
	[59] = {label = "Orbital Cannon"},
	[60] = {label = "Bomb Gas"},
	[61] = {label = "Explosive Ammo: Shotgun"},
	[62] = {label = "Oppressor 2 Cannon"},
	[63] = {label = "Mortar: Tar"},
	[64] = {label = "Vehicle Mine: Kinetic"},
	[65] = {label = "Vehicle Mine: EMP"},
	[66] = {label = "Vehicle Mine: Spike"},
	[67] = {label = "Vehicle Mine: Slick"},
	[68] = {label = "Vehicle Mine: Tar"},
	[69] = {label = "Drone"},
	[70] = {label = "Raygun"},
	[71] = {label = "Buried Mine"},
	[72] = {label = "Missile"}
}